services:
  - type: web
    name: backend
    rootDir: backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --preload --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_DEBUG
        value: 0

  - type: web
    name: frontend
    rootDir: frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: NODE_VERSION
        value: 18
